package proyecto;
/**
 *
 * @author DerekMSI
 */
public class Inicio extends javax.swing.JFrame {
    /**
     * Creates new form PanelPrincipal
     */
    Registro panelregistro;
    Facturacion panelfactura;
    Caja panelcierre;
  
    public Inicio() {
        
        initComponents();
        setLocationRelativeTo(null);
        
        //Registro de clientes
        panelregistro=new Registro();
        panelregistro.setBounds(400, 0, 1100, 900);
        add(panelregistro);
        panelregistro.setVisible(false);
        //Facturacion
        panelfactura=new Facturacion();
        panelfactura.setBounds(400,0,1100,900);
        add(panelfactura);
        //Cierre de caja
        panelcierre= new Caja();
        panelcierre.setBounds(400,0,1100,900);
        add(panelcierre);
        panelcierre.setVisible(false);
        //Imagen de fondo
        imagen_fondo.setVisible(true);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        MenuPrincipal = new javax.swing.JPanel();
        Nombre_Local = new javax.swing.JLabel();
        Boton_Registro = new javax.swing.JButton();
        Boton_Factura = new javax.swing.JButton();
        Boton_CierreCaja = new javax.swing.JButton();
        Boton_Cerrar = new javax.swing.JButton();
        Boton_Mostrar_Usuarios = new javax.swing.JButton();
        Integrantes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        imagen_fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MenuPrincipal.setBackground(new java.awt.Color(191, 165, 204));

        Nombre_Local.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        Nombre_Local.setForeground(new java.awt.Color(0, 0, 2));
        Nombre_Local.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Nombre_Local.setText("SALON DE BELLEZA");

        Boton_Registro.setText("Agendar Cita");
        Boton_Registro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_RegistroActionPerformed(evt);
            }
        });

        Boton_Factura.setText("Cobrar cita");
        Boton_Factura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_FacturaActionPerformed(evt);
            }
        });

        Boton_CierreCaja.setText("Cierre de caja");
        Boton_CierreCaja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CierreCajaActionPerformed(evt);
            }
        });

        Boton_Cerrar.setText("Cerrar");
        Boton_Cerrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_CerrarActionPerformed(evt);
            }
        });

        Boton_Mostrar_Usuarios.setText("Mostrar Citas Actuales");
        Boton_Mostrar_Usuarios.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Boton_Mostrar_UsuariosActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout MenuPrincipalLayout = new javax.swing.GroupLayout(MenuPrincipal);
        MenuPrincipal.setLayout(MenuPrincipalLayout);
        MenuPrincipalLayout.setHorizontalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(151, 151, 151)
                .addGroup(MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(Boton_Registro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Factura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_CierreCaja, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Nombre_Local, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Cerrar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(Boton_Mostrar_Usuarios, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(146, Short.MAX_VALUE))
        );
        MenuPrincipalLayout.setVerticalGroup(
            MenuPrincipalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuPrincipalLayout.createSequentialGroup()
                .addGap(75, 75, 75)
                .addComponent(Nombre_Local)
                .addGap(58, 58, 58)
                .addComponent(Boton_Registro)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_Factura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_CierreCaja)
                .addGap(84, 84, 84)
                .addComponent(Boton_Mostrar_Usuarios)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(Boton_Cerrar)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        Nombre_Local.getAccessibleContext().setAccessibleName("Nombre_local");
        Boton_Registro.getAccessibleContext().setAccessibleName("Boton_Registro");

        Integrantes.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(124, 27, 99));
        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(124, 27, 99));
        jLabel1.setText("Integrantes:");
        Integrantes.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 86, -1, 100));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(124, 27, 99));
        jLabel2.setText("- Derek Cervantes Guerrero.");
        Integrantes.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, 470, 100));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(124, 27, 99));
        jLabel3.setText("- Kevin David Arias Ramírez");
        Integrantes.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 338, 440, 60));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(124, 27, 99));
        jLabel4.setText("- Luis  Diego Chinchilla Zúñiga");
        Integrantes.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 430, 490, -1));
        Integrantes.add(imagen_fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 570, 830));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(MenuPrincipal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(38, 38, 38)
                .addComponent(Integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MenuPrincipal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(Integrantes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        MenuPrincipal.getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void Boton_RegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_RegistroActionPerformed
        // TODO add your handling code here:
        panelregistro.setVisible(true);
        setSize(1500, 865);
        panelfactura.setVisible(false);
        panelcierre.setVisible(false);
        Integrantes.setVisible(false);
        imagen_fondo.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_Boton_RegistroActionPerformed
    private void Boton_CierreCajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CierreCajaActionPerformed
        // TODO add your handling code here:
        panelregistro.setVisible(false);
        setSize(1500, 865);
        panelfactura.setVisible(false);
        panelcierre.setVisible(true);
        Integrantes.setVisible(false);
        imagen_fondo.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_Boton_CierreCajaActionPerformed
    private void Boton_CerrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_CerrarActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_Boton_CerrarActionPerformed
    private void Boton_FacturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_FacturaActionPerformed
        // TODO add your handling code here:
        panelregistro.setVisible(false);
        setSize(1500, 865);
        panelfactura.setVisible(true);
        panelcierre.setVisible(false);
        Integrantes.setVisible(false);
        imagen_fondo.setVisible(false);
        revalidate();
        repaint();
    }//GEN-LAST:event_Boton_FacturaActionPerformed
    private void Boton_Mostrar_UsuariosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Boton_Mostrar_UsuariosActionPerformed
        // TODO add your handling code here:
        TablaUsuarios mostrarinfo=new TablaUsuarios();
        mostrarinfo.setVisible(true);
        mostrarinfo.setLocationRelativeTo(null);
    }//GEN-LAST:event_Boton_Mostrar_UsuariosActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Boton_Cerrar;
    private javax.swing.JButton Boton_CierreCaja;
    private javax.swing.JButton Boton_Factura;
    private javax.swing.JButton Boton_Mostrar_Usuarios;
    private javax.swing.JButton Boton_Registro;
    private javax.swing.JPanel Integrantes;
    private javax.swing.JPanel MenuPrincipal;
    private javax.swing.JLabel Nombre_Local;
    private javax.swing.JLabel imagen_fondo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    // End of variables declaration//GEN-END:variables

}
